language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - os: osx
      python: 3.6

before_install:
  ### Update RCS keywords
  - printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
  - rm -rf src/*.c
  - git checkout src/*.c
  ### Install libomp
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_NO_INSTALL_CLEANUP=1
  - brew install libomp
  - brew link --force libomp
  ### Install CUDA
  - curl -o cuda.zip --insecure https://mcx.space/dev/ci/cuda-10-2-0.zip
  - unzip cuda.zip
  - sudo mv cuda/ /usr/local/
  - sudo chmod +x /usr/local/cuda/bin/*
  - sudo chmod +x /usr/local/cuda/nvvm/bin/*
  - CUDA_HOME=/usr/local/cuda
  - CUDA_PATH=${CUDA_HOME}/bin
  - CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
  - PATH=${CUDA_PATH}:.:${PATH}
  - ln -s /usr/local/opt/libomp/include/*.h /usr/local/cuda/include

script: 
  - cd pmcx/
  - pip3 install wheel
  - VERBOSE=1 pip wheel . -w ../dist/
  - cd ..
  - bash .github/check-pypi-upload.sh

#deploy:
#  provider: pypi
#  username: "__token__"
#  password: "Your PyPI API token, including the pypi- prefix"
