name: Build and Upload MacOS Python Wheels
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master


jobs:
  build_macos_wheels:
    name: Build MacOS Wheels
    runs-on: macos-10.13
    strategy:
      matrix:
        python_version: [ '3.6', '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install CUDA
        run: |
          brew tap homebrew/cask-drivers
          brew install nvidia-cuda-toolkit
          echo /Developer/NVIDIA/CUDA-10.2/bin >> $GITHUB_PATH
          echo "DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-10.2/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}" >> $GITHUB_ENV

      - name: Build Wheels
        run: |
          cd src/
          pip install wheel
          python setup.py bdist_wheel
          
  

#  upload_pypi:
#    needs: build_linux_wheels, build_windows_wheels
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: artifact
#          path: dist
#
#      - uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.mcx_pypi_secret }}
