name: Build and Upload Manylinux2014 Python Wheels
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master


jobs:
  build_linux_wheels:
    name: Build manylinux2014 Wheels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build Wheel Builder Container
        shell: bash
        run: |
          set -x
          cd .github/manylinux2014_wheel_builder
          docker build --tag manylinux2014_wheel_builder --force-rm .
      - name: Build Manylinux2014 Wheels
        shell: bash
        run: |
          docker run -v ${GITHUB_WORKSPACE}/src/:/src/ manylinux2014_wheel_builder
          sudo mv ${GITHUB_WORKSPACE}/src/dist/ ${GITHUB_WORKSPACE}/dist/
      - name: Check If Wheels Need to be Uploaded to PyPI
        id: perform_pypi_upload_check
        shell: bash
        run: |
          ${GITHUB_WORKSPACE}/.github/check-pypi-upload.sh
      - name: Upload packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ github.repository_owner == 'fangq' && steps.perform_pypi_upload_check.outputs.perform_pypi_upload == 1 }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify_metadata: false
          verbose: true